server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  absolute_redirect off;
  port_in_redirect on;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /v1/ {
    proxy_pass http://api-pss-dev-v1:8080/v1/;
    proxy_http_version 1.1;

    # aqui é melhor preservar porta quando existe
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /v3/ {
    proxy_pass http://api-pss-dev-v1:8080/v3/;
  }

  location /swagger-ui/ {
    proxy_pass http://api-pss-dev-v1:8080/swagger-ui/;
  }
}

